# Generated by Django 4.2.5 on 2023-09-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop3_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ATTN_Number', models.IntegerField()),
                ('Movie_Name', models.TextField(max_length=20)),
                ('Seat_Number', models.TextField(max_length=20)),
                ('Show_Time', models.TextField(max_length=20)),
            ],
        ),
    ]
